apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: risingwave-etcd-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: /disk/k8s-pvs/risingwave-etcd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: risingwave-etcd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi